version: "3"

services:
  spec:
    restart: "no"
    build:
      context: .
    volumes:
      - .:/app
    command: make -C /app spec

  pages:
    extends: spec
    command: make -C /app pages

  lint:
    restart: "no"
    image: openapitools/openapi-generator-cli
    volumes:
      - ./tmp:/local
    command: validate -i /local/rst-api-spec-internal.yaml
