version: "3"

services:
  spec:
    restart: "no"
    build:
      context: .
    volumes:
      - .:/app
    command: make -C /app spec

  pages:
    extends: spec
    command: make -C /app pages

  lint:
    restart: "no"
    image: openapitools/openapi-generator-cli
    volumes:
      - ./tmp:/local
    command: validate -i /local/rst-api-spec.yaml

  spec-persistent:
    extends: spec
    volumes:
      - rst:/tmp/rst
    environment:
      - RST_SPEC_URL=file://tmp/rst/rst-test-specs.yaml
    command: make -C /app spec

volumes:
  rst:
    external: true
    name: rst-test-spec-persistent

