openapi: 3.1.0

info:
  title: ICANN RST API
  description: |
    ICANN Registry System Testing (RST) API.
  version: 1.0.0
  termsOfService: https://icann.org/rst
  contact:
    name: Internet Corporation for Assigned Names and Numbers (ICANN)
    url: https://icann.org/rst
    email: rst@icann.org

servers:
  - url: https://api.rst.icann.org/

paths:

components:
  schemas:
    testRequest:
      description: A request for a test submitted by a client.
      type: object
      properties:
        id:
          description: Unique ID for this test request.
          type: integer
          format: uint64
          examples: [987654321]

        requester:
          description: Unique ID for the user that submitted this request.
          type: string
          examples: [example]

        dateRequested:
          description: date/time when this request was submitted.
          type: string
          format: date-time

        dateStarted:
          description: date/time when the test run started (which may be null).
          type:
            - string
            - "null"
          format: date-time

        dateCompleted:
          description: date/time when the test run finished (which may be null).
          type:
            - string
            - "null"
          format: date-time

        status:
          description: |
            The status of this request.
            1. The **requested** value indicates that the request has been received but a test run has not yet started.
            2. The **in-progress** value indicates that the test run has started but has not yet been completed.
            3. The **completed** value indicates that the test run has completed.
          type: string
          default: requested
          enum:
            - requested
            - in-progress
            - completed

        result:
          description: |
            The outcome of the test run.
            1. The **pass** value indicates that the test run completed with no errors.
            2. The **fail** value indicates that at least one test failed.
            3. The **error** value indicates that an internal issue prevented the test run from completing.
            This value will be **null** unless the value of the **status** property is **completed**.
          type:
            - string
            - "null"
          enum:
            - pass
            - fail
            - error
          default: null

        testPlan:
          description: |
            The test plan used requested.
          oneOf:
            - type: "#/components/schemas/testPlanMnemonic"
            - type: "#/components/schemas/detailedTestPlan"
  
        testParameters:
          description: |
            The test parameters provided by the requester.
          type: "#/components/schemas/testParameters"

        testResults:
          description: |
            The result of the test run.
          oneOf:
            - null
