openapi: 3.1.0

components:
  schemas:
    request:
      description: A request for a test submitted by a client.
      type: object
      properties:
        id:
          description: Unique ID for this test request.
          type: integer
          format: uint64
          examples: 987654321

        requester:
          description: Unique ID for the user that submitted this request.
          type: string
          examples: [example]

        dateRequested:
          description: date/time when this request was submitted.
          type: string
          format: date-time

        dateStarted:
          description: date/time when the test run started (which may be null).
          type:
            - string
            - "null"
          format: date-time

        dateCompleted:
          description: date/time when the test run finished (which may be null).
          type:
            - string
            - "null"
          format: date-time

        status:
          description: status of this request.
          type: string
          default: requested
          enum:
            - requested
            - in-progress
            - completed

        result:
          description: the outcome of the test.
          type:
            - string
            - "null"
          enum:
            - pass
            - fail
            - error
          default: null

        testPlan:
          description: The test plan used requested.
          default: all
          type:
            - string
            - array
          enum:
            - all
            - all_rsp
            - all_dns
            - all_proxy
          items:
            type: "#/components/schemas/plan"

        testParameters:
          description: The test parameters provided by the requester.
          type:

    plan:
      type: object
      properties:
        epp:
          description: a list of test case mnemonics relating to EPP.
          type: array
          items:
            type: "#/components/schemas/eppTestCase"
        rdap:
          description: a list of test case mnemonics relating to RDAP.
          type: array
          items:
            type: "#/components/schemas/eppTestCase"
        dns:
          description: a list of test case mnemonics relating to DNS.
          type: array
          items:
            type: "#/components/schemas/eppTestCase"
        dnssec:
          description: a list of test case mnemonics relating to EPP.
          type: array
          items:
            type: "#/components/schemas/eppTestCase"
        epp:
          description: a list of test case mnemonics relating to EPP.
          type: array
          items:
            type: "#/components/schemas/eppTestCase"
