flowchart TD
    START[START] --> |"createTest (TA)"| A
    A[inputs-needed] -->|"setTestInputParameters (RSP)"| B{inputs complete?}
    B -->|N| A
    B -->|Y| C[inputs-complete]
    C -->|"setTestStatus (RSP)"| D[ready-to-start]
    D --> |"setTestStatus (TOS)"| E1[in-progress]
    E1 --> |setTestStatus| A
    E1 --> |"setTestStatus (TOS)"| G{pass?}
    G --> |Y| H[completed]
    G --> |N| I{expired?}
    I --> |N| A
    I --> |Y| J[expired]
    H --> END
    J --> END
