flowchart TD
    START[START] --> |"createTest (TA)"| A
    A[inputs-needed] -->|"setTestInputParameters (RSP)"| B{inputs<br>complete?}
    B -->|N| A
    B -->|Y| C[inputs-complete]
    C -->|"setTestStatus"| D[ready-to-start]
    D --> |"setTestStatus"| E1[in-progress]
    E1 --> |"setTestStatus"| G{Pass?}
    G --> |Y| H[completed]
    G --> |N| I{Expired?}
    I --> |N| A
    I --> |Y| J[expired]
    H --> END
    J --> END
