sequenceDiagram
    Applicant->>RSP Portal: submit RSP<br>evaluation application

    Activate RSP Portal

    Note right of RSP Portal: ICANN org<br>reviews application

    RSP Portal->>RST-API: create new<br>test request<br>[createTest()]

    Activate RST-API
    Note right of RST-API: create test in<br>database
    RST-API->>RSP Portal: respond with<br>test request ID
    Deactivate RST-API

    RSP Portal->>Applicant: provide test<br>request ID to applicant

    Deactivate RSP Portal

    par RSP Portal monitors<br>for test result
        Activate RSP Portal

        loop 1h
            RSP Portal->>RST-API: query for results<br>[getTestInfo()]
        end

        RSP Portal->>Applicant: notice of completed test

        Deactivate RSP Portal
    and
        loop Applicant self-<br>administers the test
            Activate Applicant
            Applicant->>RST-API: submit input parameters<br>[setTestInputParameters()]
            Note right of RST-API: store parameters
            Applicant->>RST-API: upload files<br>[uploadFile()]
            Note right of RST-API: store files
            Applicant->>RST-API: initiate test<br>[startTestRun()]
            Deactivate Applicant
            par Test run
                Activate RST-TOS
                note right of RST-TOS: run test plan
                RST-TOS->>RST-API: update test result<br>[setTestStatus()]
                Deactivate RST-TOS
            and
                loop
                    Activate Applicant
                    Applicant->>RST-API: poll for results<br>[getTestInfo()]
                    critical Check test result
                    option Pass
                        Note left of Applicant: outer loop ends,<br>workflow is complete
                    option Fail
                        note left of Applicant: applicant resolves issue<br>and outer loop repeats
                    option Exception
                        Note left of Applicant: ICANN resolves issue,<br>notifies Applicant<br>out-of-band. Outer<br>loop repeats
                    end
                    Deactivate Applicant
                end
            end
        end
    end
