name: lint

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create docker volume (if needed)
        run: docker volume create rst-test-spec-persistent

      - name: build
        run: docker compose run spec

      - name: lint
        run: docker compose run lint
